# User config
author: "Colby Frashure"
tagline: "Colby Is Me"
description: "Hello! My name is Colby. I'm an audio generalist with experience in production and composition. I'm a transfer student from the University of Delaware currently at the University of Maryland, Baltimore County studying Computer Science. Despite this, I mainly pursue music and have been heavily involved with the music scene, both in my home state of Maryland and at my former University in Delaware. I hope I can apply my methodical and precise approach to client fulfillment to any of your musical needs. Scroll below to see my most notable skills."
keywords: "Music, Songwriting, Composition, Audio Production, Audio Engineering"
email: "colbyfrashure@gmail.com"
linkedin: "https://www.linkedin.com"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
