# User config
author: "Colby Frashure"
tagline: "Colby Is Me"
description: "Hello! My name is Colby. I'm an audio generalist with experience in production and composition. I'm a transfer student from the University of Delaware currently at the University of Maryland, Baltimore County studying Computer Science. Despite this, I mainly pursue music and have been heavily involved with the music scene, both in my home state of Maryland and at my former University in Delaware. I hope I can apply my creatively analytical approach of client fulfillment to any of your musical needs. Scroll below to see my most notable skills."
keywords: "Music, Songwriting, Composition, Audio Production, Audio Engineering"
email: "colbyfrashure@gmail.com"
youtube: "https://youtube.com/@localorange"
instagram: "https://instagram.com/c_frashure"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
